__all__ = ["RELEASE_ASSET_NAME", "RELEASE_EXECUTABLE_NAME", "REPO_OWNER", "REPO_NAME"]

RELEASE_ASSET_NAME = "quickfund-win64.zip"
RELEASE_EXECUTABLE_NAME = "基金信息生成器.exe"

REPO_OWNER = "MapleCCC"
REPO_NAME = "QuickFund"
